# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MalayaliDinoGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MalayaliDinoGame
	pod 'SwiftyJSON'

end

# Ensure all pods use the same iOS deployment target
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
